### ISSUE TITLE
Use velocities and accelerations from yarp controlboard instead of using filters

### ISSUE THREAD

**Issue by traversaro** [robotology-playground/yarp-wholebodyinterface#12]
It appears that at least velocities that we get from the firmware for iCub v1/v2 are ok.

We have then to modify the yarpWholeBodyState to optionally get velocities and perhaps accelerations from `getEncoderVelocities` and `getEncoderAccelerations` methods if this are available (i.e. if broadcast_vel_acc is set to 1). 

However we have to wait that velocities and acceleration are broadcasted as part of the state instead of exposed via RPC, i.e. we have to wait until https://github.com/robotology/yarp/tree/ControlBoardWrapper2_NewOutputPort yarp branch is merged.

**Comment by traversaro** [comment]
@francesco-romano @DanielePucci
 the branch for broadcasting velocity and accelerations have been merged in yarp , and we also now have motor-side velocities.
Further considerations: if accelerations are not available, we should estimated them with a linear estimation filter on the velocity readings, so we can get rid of the performancy penalty given by the adaptive windows filter.

**Comment by traversaro** [comment]
cc @DanielePucci

**Comment by iron76** [comment]
The task has been assigned to @nunoguedelha

**Comment by traversaro** [comment]
Brief explanation (warning: ugly design ahead, any kind of improvement is more then welcome!) :
  * the [iWholeBodyStates](http://wiki.icub.org/codyco/dox/html/classwbi_1_1iWholeBodyStates.html) is a C++ interface (i.e. a pure virtual class) of an object exposing estimates of the robot quantities (joint positions, joint velocities, torques, external forces etc etc.
  * in yarpWholeBodyInterface, there are two implementations of this interface:
    * [yarpWholeBodyStates](http://wiki.icub.org/codyco/dox/html/classyarpWbi_1_1yarpWholeBodyStates.html) is the default version, used by all the modules. 
  * [yarpWholeBodyStatesLocal](http://wiki.icub.org/codyco/dox/html/classyarpWbi_1_1yarpWholeBodyStatesLocal.html)
 used only by the wholeBodyDynamicsTree module. 

The only difference between the two classes is that while the yarpWholeBodyStates implementation reads the torques directly  from the robotInterface, the yarpWholeBodyStatesLocal reads joint positions and FT sensors measures from the robot, and using this measures it estimates the joint torques. This estimates are then send by the wholeBodyDynamicsTree module to the robotInterface.

This means that most of the code is duplicated between yarpWholeBodyStates and yarpWholeBodyStatesLocal  . : (

**Comment by nunoguedelha** [comment]
As getting the velocities and accelerations broadcasted by the controlBoard is meant to be an option, do we want to use an internal attribute/flag like `motor_quantites_estimation_enabled` in the class `yarpWholeBodyEstimator`?

**Comment by traversaro** [comment]
Yes, and I would load it from configuration files as we do for `getLimitsFromControlBoard` option in `yarpWholeBodyModel`: 
 https://github.com/robotology-playground/yarp-wholebodyinterface/blob/29529c9a0cb5dd1f94f6f3d03c07f24ca97069a9/src/yarpWholeBodyModel.cpp#L142

**Comment by traversaro** [comment]
@nunoguedelha It make sense. Given that (for now) the wholeBodyInterface is just used in the codyco-superbuild, just make sure that you renaming that enum value in all subprojects.

**Comment by nunoguedelha** [comment]
I've pushed into my branch (`CR12_veloc_n_acc_fromyarp_controlboard`) the wholeBodyInterface and yarpWholeBodyInterface code for reading the velocities and accelerations. I'm doing a pull request only for a first review. I'm not calling the `getEncoderSpeedsTimed` and `getEncoderAccelerationsTimed` in `yarpWholeBodySensors::readEncoders` implementation because these methods don't seem to be implemented yet in `IEncodersTimedImpl.cpp`. I only found the implementations without the timestamps handling, as for the respective methods reading the raw data (`getEncoderAccelerationRaw`, ... implemented in `CanBusMotionControl` class). Is there any branch implementing the missing functions? If not I'll implement it following the exiting ones.

**Comment by DanielePucci** [comment]
+1

**Comment by traversaro** [comment]
cc @barbalberto probably knows if the `getEncoderSpeedsTimed` and `getEncodersAccelerationsTimed` are properly implemented in the `RemoteControlBoard` and in `CanBusMotionControl` and `embObjMotionControl`. For now just calling `getEncoderSpeeds`/`getEncoderAccelerations` and then using the timestamps from the getEncoders call is ok, even because they all come from the same message published on the `stateExt:o` port.

**Comment by barbalberto** [comment]
They do not exists at all :)
Which timestamp are you interested in? 
As far as I understand by reading the code, the encoderTimed function gives the time in which the value is received by the pc104. For the speed and acceleration this is not handled at the can device level and therefore not broadcasted on yarp.

If the time on which the data is sent by the robotInterface yarp port is enough for you, using the extended port (default now) it is the same for all the data broadcasted, so it is the same for position, velocity and acceleration. You can simply read the envelop time.
Obviously it does not perfectly match the time the acquisition took place, but that time is unknown any way

**Comment by traversaro** [comment]
Code by @nunoguedelha merged in https://github.com/robotology-playground/yarp-wholebodyinterface/commit/4f9c540dc7c3798692abb89f578952386fa04dfd . 
A `readSpeedAccFromControlBoard` should be added to the wbi configuration file to read speed and accelerations from the controlBoards.
