### ISSUE TITLE
[yarpWholeBodyStates] Matlab crashes when using velocities from firmware

### ISSUE THREAD

**Issue by DanielePucci** [robotology-playground/yarp-wholebodyinterface#27]
> Stack Trace (from fault):
> [  0] 0x00007f74adacaba3 /home/shared/build-x86_64/codyco-superbuild/install/mex/../lib/libyarpwholebodyinterface.so.0.2.1+00322467 _ZN7yarpWbi20yarpWholeBodySensors12readEncodersENS_1$
> [  1] 0x00007f74adab5ffb /home/shared/build-x86_64/codyco-superbuild/install/mex/../lib/libyarpwholebodyinterface.so.0.2.1+00237563 _ZN7yarpWbi22yarpWholeBodyEstimator3runEv+00001179
> [  2] 0x00007f74ace84952 /home/shared/build-x86_64/yarp/lib/libYARP_OS.so.1+01243474 _ZN25RateThreadCallbackAdapter3runEv+00000178
> [  3] 0x00007f74acebb45c /home/shared/build-x86_64/yarp/lib/libYARP_OS.so.1+01467484 _Z18theExecutiveBranchPv+00000092
> [  4] 0x00007f74a9512636                           /usr/lib/libACE-6.0.3.so+01037878 _ZN21ACE_OS_Thread_Adapter6invokeEv+00000166

**Comment by francesco-romano** [comment]
cc @nunoguedelha
