### ISSUE TITLE
[ESTIMATE_BASE_VEL] reference frame.

### ISSUE THREAD

**Issue by rlober** [robotology-playground/yarp-wholebodyinterface#36]
Hey @naveenoid 

What reference frame is the floating base state expressed in? 

Ryan

**Comment by traversaro** [comment]
In theory is the orientation of the world frame, and with respect to the origin of the base frame.

**Comment by traversaro** [comment]
For more detailed docs : http://wiki.icub.org/codyco/dox/html/dynamics_notation.html .

**Comment by rlober** [comment]
I will take a look - just trying to debug some floating base issues. Thanks @traversaro.
